//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cookie
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string IPv4 { get; set; }
        public byte[] SecretKey { get; set; }
        public System.DateTime DateOfExpiry { get; set; }
    
        public virtual User User { get; set; }
    }
}
