//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditedMessage
    {
        public long Id { get; set; }
        public Nullable<long> MessageId { get; set; }
        public Nullable<long> RepliedMessageId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Message Message1 { get; set; }
        public virtual RepliedMessage RepliedMessage { get; set; }
    }
}
