//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepliedMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepliedMessage()
        {
            this.EditedMessages = new HashSet<EditedMessage>();
            this.Notifications = new HashSet<Notification>();
            this.RepliedMessage1 = new HashSet<RepliedMessage>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<long> MessageId { get; set; }
        public Nullable<long> RepliedMessageId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EditedMessage> EditedMessages { get; set; }
        public virtual Message Message1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepliedMessage> RepliedMessage1 { get; set; }
        public virtual RepliedMessage RepliedMessage2 { get; set; }
        public virtual User User { get; set; }
    }
}
